# Generated by Django 5.2 on 2025-04-21 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_article_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
    ]
